---
deploy_repo_path: /opt/amneziawg-docker
docker_compose_version: "v2.29.0"

vpn_port: 51820
vpn_address: "10.13.13.1/24"
vpn_jc: 4
vpn_jmin: 40
vpn_jmax: 70

dockerhub_image: "changeme/amneziawg-docker"
dockerhub_tag: "latest"
